### ISSUE TITLE
Setup file reported as "Malicious" by Trend Micro

### ISSUE THREAD

**Issue by mdaghrir** [justinevedovato/Helium-Flick#5]
Trend Micro is reporting the install file as malicious when trying to perform its install.
Is there something on the code that needs to be corrected to avoid that alert?

![Malicious](https://user-images.githubusercontent.com/1776492/146941413-a55307ac-58ff-4ce2-895b-97a15b3acf41.JPG)

**Comment by justinevedovato** [comment]
Hello! There is nothing inside the code related to this, but you are simply having this message because the application doesn't have a certificate. Those can be quite expensive, so I chose not to get one, for an open-source side project like this. I believe everyone is having the same warning, which is a basic security feature. But if you have any doubt (which is totally normal) you can clone the project and build it locally, it is explained in the description :)
