### ISSUE TITLE
Hotspot list sorting

### ISSUE THREAD

**Issue by bkhall** [justinevedovato/Helium-Flick#8]
Add some controls to sort the list of hotspots.

I realize most people have only a few hotspots, but larger lists (10 or so) need the ability to sort the list.

- daily earnings
- total earnings
- hotspot name
- hotspot brand
- online/offline

You get the idea...

**Comment by justinevedovato** [comment]
Thank you for your suggestion! I will have a look into this.
Usually, sorting of that kind is delivered by the backend, and doing it in the frontend might get a bit tricky, mostly when the data allowing the sorting has to be fully fetched for all hotspots of the list before being able to being sorted.
So if one hotspot of the list isn't fetched, the whole list won't show at all, because the sorting can't be done. As of today, if one hotspot isn't fetched, it stays in a loading state but you can still see all the others.
I will still look and see what I can do!

**Comment by justinevedovato** [comment]
Hello!
Sorting is now included in the app, for Status, daily earnings and total earnings!
I decided to not sort by name or brand, as those are not values that are going to change, so if you want your hotspots in a specific order, you can drag and drop them in the Settings page and arrange the list as you like. This sorting preference (by drag and drop) will be named as "default", and the app will always show your hotspots in this order when you open the page.

I wanted to keep the sorting for changing values, to make it easier to see online/offline hotspots, or who has the most earnings, etc.
Anyway thanks for the sorting suggestion!

**Comment by bkhall** [comment]
Looks great - thank you. This can be closed.
