### ISSUE TITLE
Hotspots not loading since Blockchain Updates

### ISSUE THREAD

**Issue by Jijkz** [justinevedovato/Helium-Flick#9]
Hi,
I love this small tool and use it every day to monitor my hotspots!

Since the 28th of march (I believe), all of my added hotspots are in an endless loading loop. Reinstalling the application or removing and readding hotspots manually did not help, since I can't add hotspots at all anymore.

Probably coincidentally, around that time the Helium Devs made a buch of Changes, e.g. Testnet Restart, HIP 54 Activation Delay. I don't see how a Testnet restart would affect the App/API; perhaps it did, perhaps it's just a coincidence. But I thought it's worth mentioning.

**Comment by justinevedovato** [comment]
Hello! Thank you for using the app!
Indeed It isn't working for me either, they seem to be using a different API now, without any notice from what I can see. I have no ways to know if this is just a temporary URL or not, and how long it will take until it changes again, but at least I will fix this and push an update asap!

**Comment by justinevedovato** [comment]
Thanks!
It's not completely on them cause I decided to use the API they are using on the explorer rather than the one they give in their documentation. Both are public, so I can technically use both, but the one I chose is much faster. This is the one they seemed to have replaced recently, so they didn't **have** to specify that they would be changing it, as they are supposedly the only ones using it (which I doubt, cause it's public!).
So in that case it's on me, if I used their normal API it would still work. It would be super slow, but at least working!
I'd like to see if I can use it as a fallback if the first one fails, but this is gonna require some testing to make sure it works well (and doesn't break and calls endlessly), so probably an idea for another update in the future!
